#name: Tian's Jekyll Site
#permalink: pretty
permalink: /:year/:month/:title/
markdown: kramdown
url: http://tiancao.me/blog
#baseurl: http://tiancao.me/blog
author: Tian Cao
highlighter: rouge
exclude: ['Rakefile.rb', 'CNAME', 'README.markdown']

# site config
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png
